name: CI – Build & Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]  
  push:
    branches: [ "master" ]

concurrency:
  group: ci-buildtest-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  USE_LOCKED_MODE: 'false'

jobs:
  build-test:
    name: Build & Test (.NET 9)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            **/*.sln
            **/*.csproj
            **/global.json
            **/nuget.config

      - name: Restore
        run: |
          if [ "${USE_LOCKED_MODE}" = "true" ]; then
            dotnet restore --locked-mode
          else
            dotnet restore
          fi

      - name: Build (Release, warnings as errors)
        run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true

      - name: Test (XPlat Coverage)
        run: >
          dotnet test --configuration Release --no-build
          --collect:"XPlat Code Coverage"
          --logger "trx;LogFileName=test-results.trx"

      - name: Locate coverage file
        id: coverage
        run: |
          FILE=$(find . -type f -name "coverage.cobertura.xml" | head -n1 || true)
          echo "file=${FILE}" >> "$GITHUB_OUTPUT"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: warn
          path: |
            **/TestResults/*.trx
            **/TestResults/*/coverage.cobertura.xml
            ${{ steps.coverage.outputs.file }}

  e2e-tests:
    if: github.event_name == 'pull_request'
    name: Gateway E2E Tests (.NET 9)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            **/*.sln
            **/*.csproj
            **/global.json
            **/nuget.config

      - name: Restore
        run: |
          if [ "${USE_LOCKED_MODE}" = "true" ]; then
            dotnet restore --locked-mode
          else
            dotnet restore
          fi

      - name: Build Gateway & E2E Tests
        run: >
          dotnet build
          src/gateway/Gateway.csproj
          tests/Gateway.E2ETests/Gateway.E2ETests.csproj
          --configuration Release --no-restore

      - name: Test (E2E)
        run: >
          dotnet test tests/Gateway.E2ETests --configuration Release
          --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          if-no-files-found: warn
          path: |
            **/TestResults/*.trx
