name: Deploy infra + apps

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

permissions:
  id-token: write    # necessario per OIDC
  contents: read

env:
  RG: aegisapi-rg
  LOCATION: eastus
  PREFIX: aegis
  # login server deterministico per l'ACR <prefix>acr
  LOGIN_SERVER: ${{ env.PREFIX }}acr.azurecr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del codice
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Login in Azure via OIDC (usa i 3 secrets che hai creato)
      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3) Info di contesto
      - name: Show Azure context
        run: |
          az account show
          az --version

      # 4) Crea/aggiorna il Resource Group (idempotente)
      - name: Ensure Resource Group
        run: |
          az group create -n $RG -l $LOCATION

      # 5a) Compila Bicep -> ARM JSON (aggira bug validate/what-if)
      - name: Compile Bicep to JSON
        run: |
          mkdir -p out
          az bicep build --file infra/main.bicep --outdir out
          ls -la out

      # 5b) Validate sul JSON compilato
      - name: Validate compiled template
        run: |
          az deployment group validate \
            -g $RG \
            --template-file out/main.json \
            --parameters namePrefix=$PREFIX \
                         gatewayImage=$LOGIN_SERVER/gateway:latest \
                         summarizerImage=$LOGIN_SERVER/summarizer:latest \
                         dashboardImage=$LOGIN_SERVER/dashboard:latest

      # 5c) Deploy reale (debug attivo)
      - name: Deploy compiled template (apply with debug)
        env:
          AZURE_CORE_COLLECT_TELEMETRY: "false"
        run: |
          az deployment group create \
            -g $RG \
            --template-file out/main.json \
            --parameters namePrefix=$PREFIX \
                         gatewayImage=$LOGIN_SERVER/gateway:latest \
                         summarizerImage=$LOGIN_SERVER/summarizer:latest \
                         dashboardImage=$LOGIN_SERVER/dashboard:latest \
            --debug

      # 6) Concedi al workflow il ruolo dati su Key Vault (per poter fare secret set)
      - name: Grant Key Vault data-plane role to OIDC app
        run: |
          KEYVAULT_NAME="${PREFIX}-kv"
          KV_ID=$(az keyvault show -n "$KEYVAULT_NAME" --query id -o tsv)
          az role assignment create \
            --assignee ${{ secrets.AZURE_CLIENT_ID }} \
            --role "Key Vault Secrets Officer" \
            --scope "$KV_ID" \
          || true

      # 7) Imposta il secret in Key Vault (consumato dalle app via KeyVault reference)
      - name: Seed Key Vault secret
        run: |
          KEYVAULT_NAME="${PREFIX}-kv"
          az keyvault secret set --vault-name "$KEYVAULT_NAME" --name sample-secret --value "changeme-from-gha"

      # 8) Build & push immagini su ACR (ACR si chiama sempre <prefix>acr)
      - name: Build and Push Images
        run: |
          ACR_NAME="${PREFIX}acr"
          az acr build -r "$ACR_NAME" -t gateway:latest path/to/gateway
          az acr build -r "$ACR_NAME" -t summarizer:latest path/to/summarizer
          az acr build -r "$ACR_NAME" -t dashboard:latest path/to/dashboard

      # 9) Aggiorna le Container Apps alle nuove immagini (nuova revisione, ricarica secrets)
      - name: Roll apps to new images & refresh secrets
        run: |
          az containerapp update -n "${PREFIX}-gateway" -g $RG --image "$LOGIN_SERVER/gateway:latest"
          az containerapp update -n "${PREFIX}-summarizer" -g $RG --image "$LOGIN_SERVER/summarizer:latest"
          az containerapp update -n "${PREFIX}-dashboard" -g $RG --image "$LOGIN_SERVER/dashboard:latest"

      # 10) Stampa gli endpoint pubblici (gateway, dashboard)
      - name: Show endpoints
        run: |
          GATEWAY_FQDN=$(az containerapp show -n "${PREFIX}-gateway" -g $RG --query properties.configuration.ingress.fqdn -o tsv)
          DASHBOARD_FQDN=$(az containerapp show -n "${PREFIX}-dashboard" -g $RG --query properties.configuration.ingress.fqdn -o tsv)
          echo "Gateway:   https://${GATEWAY_FQDN}"
          echo "Dashboard: https://${DASHBOARD_FQDN}"
