name: Deploy infra + apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  id-token: write   # necessario per OIDC
  contents: read

env:
  RG: aegisapi-rg
  LOCATION: eastus
  PREFIX: aegis
  LOGIN_SERVER: ${{ env.PREFIX }}acr.azurecr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del codice
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Login in Azure via OIDC (usa i 3 secrets che hai creato)
      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3) Az CLI info utili (verifica contesto)
      - name: Show Azure context
        run: |
          az account show
          az --version

      # 4) Crea/aggiorna il Resource Group (idempotente)
      - name: Ensure Resource Group
        run: |
          az group create -n $RG -l $LOCATION

      # 5a) Compila Bicep -> ARM JSON
      - name: Compile Bicep to JSON
        run: |
          mkdir -p out
          az bicep build --file infra/main.bicep --outdir out
          ls -la out

      # 5b) Validate sul JSON compilato
      - name: Validate compiled template
        run: |
          ACR_NAME="${PREFIX}acr"
          LOGIN_SERVER=$(az acr show -n "$ACR_NAME" --query loginServer -o tsv 2>/dev/null || true)
          if [ -z "$LOGIN_SERVER" ]; then LOGIN_SERVER="${ACR_NAME}.azurecr.io"; fi
          az deployment group validate \
          -g $RG \
          --template-file out/main.json \
          --parameters namePrefix=$PREFIX \
                       gatewayImage=$LOGIN_SERVER/gateway:latest \
                       summarizerImage=$LOGIN_SERVER/summarizer:latest \
                       dashboardImage=$LOGIN_SERVER/dashboard:latest

      # 5c) Deploy reale (debug attivo)
      - name: Deploy compiled template (apply with debug)
        env:
          AZURE_CORE_COLLECT_TELEMETRY: "false"
        run: |
          ACR_NAME="${PREFIX}acr"
          LOGIN_SERVER=$(az acr show -n "$ACR_NAME" --query loginServer -o tsv 2>/dev/null || true)
          if [ -z "$LOGIN_SERVER" ]; then LOGIN_SERVER="${ACR_NAME}.azurecr.io"; fi
          az deployment group create \
            az deployment group validate \
            -g $RG \
            --template-file out/main.json \
            --parameters namePrefix=$PREFIX \
                         gatewayImage=$LOGIN_SERVER/gateway:latest \
                         summarizerImage=$LOGIN_SERVER/summarizer:latest \
                         dashboardImage=$LOGIN_SERVER/dashboard:latest
            --debug


      # 6) Imposta il secret in Key Vault
      #    Cosa fa: scrive "sample-secret" nel KV creato (richiesto dalle app nel tuo Bicep)
      - name: Seed Key Vault secret
        run: |
          KEYVAULT_NAME="${PREFIX}-kv"
          az keyvault secret set --vault-name "$KEYVAULT_NAME" --name sample-secret --value "changeme-from-gha"

      # 7) Recupera il login server ACR (ora esiste sicuramente)
      - name: Get ACR login server
        id: acr
        run: |
          ACR_NAME="${PREFIX}acr"
          LOGIN_SERVER=$(az acr show -n "$ACR_NAME" --query loginServer -o tsv)
          echo "LOGIN_SERVER=$LOGIN_SERVER" >> $GITHUB_OUTPUT

      # 8) Build & push immagini su ACR (usa ACR Tasks remoti)
      #    Cosa fa: costruisce le tre immagini e le tagga :latest
      - name: Build and Push Images
        run: |
          ACR_NAME="${PREFIX}acr"
          az acr build -r "$ACR_NAME" -t gateway:latest path/to/gateway
          az acr build -r "$ACR_NAME" -t summarizer:latest path/to/summarizer
          az acr build -r "$ACR_NAME" -t dashboard:latest path/to/dashboard

      # 9) Aggiorna le Container Apps alle nuove immagini e forza reload secrets
      #    Cosa fa: genera una nuova revisione per ciascuna app
      - name: Roll apps to new images & refresh secrets
        run: |
          LOGIN_SERVER="${{ steps.acr.outputs.LOGIN_SERVER }}"
          az containerapp update -n "${PREFIX}-gateway" -g $RG --image "$LOGIN_SERVER/gateway:latest"
          az containerapp update -n "${PREFIX}-summarizer" -g $RG --image "$LOGIN_SERVER/summarizer:latest"
          az containerapp update -n "${PREFIX}-dashboard" -g $RG --image "$LOGIN_SERVER/dashboard:latest"

      # 10) Stampa gli endpoint pubblici (gateway, dashboard)
      - name: Show endpoints
        run: |
          GATEWAY_FQDN=$(az containerapp show -n "${PREFIX}-gateway" -g $RG --query properties.configuration.ingress.fqdn -o tsv)
          DASHBOARD_FQDN=$(az containerapp show -n "${PREFIX}-dashboard" -g $RG --query properties.configuration.ingress.fqdn -o tsv)
          echo "Gateway:   https://${GATEWAY_FQDN}"
          echo "Dashboard: https://${DASHBOARD_FQDN}"

      - name: Grant Key Vault data-plane role to OIDC app
        run: |
           KEYVAULT_NAME="${PREFIX}-kv"
           KV_ID=$(az keyvault show -n "$KEYVAULT_NAME" --query id -o tsv)
           # Ruolo dati: Key Vault Secrets Officer (consente SET/GET/DELETE segreti)
           az role assignment create \
             --assignee ${{ secrets.AZURE_CLIENT_ID }} \
             --role "Key Vault Secrets Officer" \
             --scope "$KV_ID"
