name: Deploy infra + apps

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  RG: aegisapi-rg
  LOCATION: eastus
  PREFIX: aegis

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure context
        run: |
          az account show
          az --version

      - name: Ensure Resource Group
        run: |
          az group create -n $RG -l $LOCATION

      - name: Compile Bicep to JSON
        run: |
          mkdir -p out
          az bicep build --file infra/main.bicep --outdir out
          ls -la out
          jq 'keys' out/main.json >/dev/null 2>&1 || true  # touch the file to ensure readable

      - name: Deploy compiled template (apply with debug)
        env:
          AZURE_CORE_COLLECT_TELEMETRY: "false"
        run: |
          set -x
          LOGIN_SERVER="${PREFIX}acr.azurecr.io"
          az deployment group create \
            -g $RG \
            --template-file out/main.json \
            --parameters namePrefix=$PREFIX \
                         gatewayImage=$LOGIN_SERVER/gateway:latest \
                         summarizerImage=$LOGIN_SERVER/summarizer:latest \
                         dashboardImage=$LOGIN_SERVER/dashboard:latest \
            --debug

      - name: Grant Key Vault data-plane role to OIDC app
        run: |
          KEYVAULT_NAME="${PREFIX}-kv"
          KV_ID=$(az keyvault show -n "$KEYVAULT_NAME" --query id -o tsv)
          az role assignment create \
            --assignee ${{ secrets.AZURE_CLIENT_ID }} \
            --role "Key Vault Secrets Officer" \
            --scope "$KV_ID" \
          || true

      - name: Seed Key Vault secret
        run: |
          KEYVAULT_NAME="${PREFIX}-kv"
          az keyvault secret set --vault-name "$KEYVAULT_NAME" --name sample-secret --value "changeme-from-gha"

      - name: Build and Push Images
        run: |
          ACR_NAME="${PREFIX}acr"
          az acr build -r "$ACR_NAME" -t gateway:latest path/to/gateway
          az acr build -r "$ACR_NAME" -t summarizer:latest path/to/summarizer
          az acr build -r "$ACR_NAME" -t dashboard:latest path/to/dashboard

      - name: Roll apps to new images & refresh secrets
        run: |
          LOGIN_SERVER="${PREFIX}acr.azurecr.io"
          az containerapp update -n "${PREFIX}-gateway" -g $RG --image "$LOGIN_SERVER/gateway:latest"
          az containerapp update -n "${PREFIX}-summarizer" -g $RG --image "$LOGIN_SERVER/summarizer:latest"
          az containerapp update -n "${PREFIX}-dashboard" -g $RG --image "$LOGIN_SERVER/dashboard:latest"

      - name: Show endpoints
        run: |
          GATEWAY_FQDN=$(az containerapp show -n "${PREFIX}-gateway" -g $RG --query properties.configuration.ingress.fqdn -o tsv)
          DASHBOARD_FQDN=$(az containerapp show -n "${PREFIX}-dashboard" -g $RG --query properties.configuration.ingress.fqdn -o tsv)
          echo "Gateway:   https://${GATEWAY_FQDN}"
          echo "Dashboard: https://${DASHBOARD_FQDN}"
